services:
  - type: web
    name: backoffice
    env: node
    repo: https://github.com/teach-hub/backoffice.git # optional
    region: ohio
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    numInstances: 1
    healthCheckPath: /

databases:
  - name: backoffice-db
    region: ohio
    plan: free
    databaseName: main_db_backoffice
    user: root
