services:
  - type: web
    name: backoffice
    env: node
    repo: https://github.com/teach-hub/backoffice.git # optional
    region: ohio
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    numInstances: 1
    healthCheckPath: /
